[ tool.gilesbot ]
    [ tool.gilesbot.circleci_artifacts.website ]
        url = "web/output/index.html"
        message = "Preview the built website here. Links may need appending '/index.html' to the URL."
        report_on_fail = true
